cmake_minimum_required(VERSION 3.24)
# Qt installations may be universal even though the application targets arm64.
# Thin copied bundles only; never modify the installed Qt SDK.
if(NOT IS_DIRECTORY "${APP_BUNDLE}/Contents")
    message(FATAL_ERROR "Missing staged application: ${APP_BUNDLE}")
endif()
file(GLOB_RECURSE files LIST_DIRECTORIES FALSE "${APP_BUNDLE}/Contents/*")
foreach(file IN LISTS files)
    if(IS_SYMLINK "${file}")
        continue()
    endif()
    execute_process(COMMAND /usr/bin/file -b "${file}" OUTPUT_VARIABLE type COMMAND_ERROR_IS_FATAL ANY)
    if(NOT type MATCHES "Mach-O")
        continue()
    endif()
    execute_process(COMMAND /usr/bin/lipo -archs "${file}" OUTPUT_VARIABLE architectures
        OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    if(NOT architectures MATCHES "(^| )arm64($| )")
        message(FATAL_ERROR "Missing arm64 code: ${file}")
    endif()
    if(NOT architectures STREQUAL "arm64")
        execute_process(COMMAND /usr/bin/lipo "${file}" -thin arm64 -output "${file}.thin" COMMAND_ERROR_IS_FATAL ANY)
        file(RENAME "${file}.thin" "${file}")
    endif()
endforeach()
