cmake_minimum_required(VERSION 3.24)
# A deploy command succeeding is not enough: reject external runtime dependencies.
foreach(required IN ITEMS
    "Contents/MacOS/${APP_NAME}"
    "Contents/Resources/qt.conf"
    "Contents/Resources/Licenses/ControlPanel-GPL-3.0.txt"
    "Contents/Frameworks/QtCore.framework/Versions/A/QtCore"
    "Contents/Frameworks/QtGui.framework/Versions/A/QtGui"
    "Contents/Frameworks/QtWidgets.framework/Versions/A/QtWidgets"
    "Contents/PlugIns/platforms/libqcocoa.dylib"
    "Contents/PlugIns/styles/libqmacstyle.dylib")
    if(NOT EXISTS "${APP_BUNDLE}/${required}")
        message(FATAL_ERROR "Incomplete bundle: ${required}")
    endif()
endforeach()
file(REAL_PATH "${APP_BUNDLE}" bundle_root)
file(GLOB_RECURSE files LIST_DIRECTORIES FALSE "${APP_BUNDLE}/Contents/*")
set(binary_count 0)
foreach(file IN LISTS files)
    if(IS_SYMLINK "${file}")
        file(REAL_PATH "${file}" resolved)
        string(FIND "${resolved}" "${bundle_root}/" inside)
        if(NOT inside EQUAL 0)
            message(FATAL_ERROR "Bundle symlink escapes the application: ${file}")
        endif()
    endif()
    execute_process(COMMAND /usr/bin/file -b "${file}" OUTPUT_VARIABLE type COMMAND_ERROR_IS_FATAL ANY)
    if(NOT type MATCHES "Mach-O")
        continue()
    endif()
    # Creator contains a standalone runtime bundle with its own dependency root.
    # Resolve @rpath/@executable_path against the innermost app, not Creator.
    set(binary_bundle "${APP_BUNDLE}")
    if(file MATCHES "^(.*\\.app)/Contents/")
        set(binary_bundle "${CMAKE_MATCH_1}")
    endif()
    math(EXPR binary_count "${binary_count} + 1")
    execute_process(COMMAND /usr/bin/lipo -archs "${file}" OUTPUT_VARIABLE architectures COMMAND_ERROR_IS_FATAL ANY)
    string(STRIP "${architectures}" architectures)
    if(NOT architectures STREQUAL "arm64")
        message(FATAL_ERROR "Expected arm64 only, found ${architectures}: ${file}")
    endif()
    execute_process(COMMAND /usr/bin/otool -L "${file}" OUTPUT_VARIABLE dependencies COMMAND_ERROR_IS_FATAL ANY)
    # Architecture headings also contain the file path, but dependency lines are indented.
    string(REPLACE "\n" ";" lines "${dependencies}")
    foreach(line IN LISTS lines)
        if(NOT line MATCHES "^[ \t]+(.+) \\(compatibility version")
            continue()
        endif()
        set(dependency "${CMAKE_MATCH_1}")
        if(dependency MATCHES "^/(usr/lib/|System/Library/)")
            continue()
        elseif(dependency MATCHES "^@rpath/(.+)$")
            set(resolved "${binary_bundle}/Contents/Frameworks/${CMAKE_MATCH_1}")
        elseif(dependency MATCHES "^@loader_path/(.+)$")
            get_filename_component(parent "${file}" DIRECTORY)
            set(resolved "${parent}/${CMAKE_MATCH_1}")
        elseif(dependency MATCHES "^@executable_path/(.+)$")
            set(resolved "${binary_bundle}/Contents/MacOS/${CMAKE_MATCH_1}")
        else()
            message(FATAL_ERROR "External runtime dependency in ${file}: ${dependency}")
        endif()
        if(NOT EXISTS "${resolved}")
            message(FATAL_ERROR "Missing embedded dependency in ${file}: ${dependency}")
        endif()
        file(REAL_PATH "${resolved}" real_dependency)
        string(FIND "${real_dependency}" "${bundle_root}/" inside)
        if(NOT inside EQUAL 0)
            message(FATAL_ERROR "Dependency escapes the application: ${dependency}")
        endif()
    endforeach()
    execute_process(COMMAND /usr/bin/otool -l "${file}" OUTPUT_VARIABLE commands COMMAND_ERROR_IS_FATAL ANY)
    string(REGEX MATCHALL "cmd LC_RPATH[^\n]*\n[^\n]*\n[^\n]*" rpaths "${commands}")
    foreach(rpath IN LISTS rpaths)
        if(rpath MATCHES "path /" OR NOT rpath MATCHES "path @(executable|loader)_path/")
            message(FATAL_ERROR "External runtime search path in ${file}: ${rpath}")
        endif()
    endforeach()
    execute_process(COMMAND /usr/bin/vtool -show-build "${file}" OUTPUT_VARIABLE build_versions COMMAND_ERROR_IS_FATAL ANY)
    string(REGEX MATCHALL "minos[ \t]+[0-9]+(\\.[0-9]+)*" minimums "${build_versions}")
    if(NOT minimums)
        message(FATAL_ERROR "No inspectable macOS deployment target: ${file}")
    endif()
    foreach(minimum IN LISTS minimums)
        string(REGEX REPLACE "^minos[ \t]+" "" minimum "${minimum}")
        if(minimum VERSION_GREATER "13.0")
            message(FATAL_ERROR "${file} requires macOS ${minimum}, above the advertised 13.0 minimum")
        endif()
    endforeach()
endforeach()
execute_process(COMMAND /usr/bin/codesign --verify --deep --strict "${APP_BUNDLE}" COMMAND_ERROR_IS_FATAL ANY)
message(STATUS "Verified ${APP_NAME}: ${binary_count} binaries, embedded dependencies, ${ARCH}, signature")
